### ISSUE TITLE
Configuration to add internal sites

### ISSUE THREAD

**Issue by patricematignon** [cgrail/github-chrome-fullname#2]
Hi!
Love the plugin when using the corporate GitHub Enterprise instance in particular. 
I have other internal sites that display I/C/D# and I would love to be able to just add them to a local or shared configuration for the plugin and simply enjoy the same automatic benefit.
Or maybe even a marker / config file at the root of the http service (e.g. http[s]://internalsite.sap.corp/fullname.txt) to activate the plugin for that site, if that is in the realm of possibilities.
Thanks for your feedback

**Comment by cgrail** [comment]
Hi @patricematignon I've thought about introducing the possiblity to configure the extension. But I didn't have the chance to do it now. I don't want to run it for every site as it might slow down Chrome, because it needs to do a lookup for that file. What I can do for now, is to add your url to the list of urls which activate the extension. Currently those two urls are:
```
https://github.wdf.sap.corp/*
and
https://huboard.mo.sap.corp/*
```

See also: 
https://github.com/cgrail/github-chrome-fullname/blob/master/github-chrome-fullname/manifest.json#L15

Either do a PR and add the url by your own or send me the url you'd like to add.

**Comment by patricematignon** [comment]
That would be great, thanks!

Do you know whether it could accept domain names, e.g. :
`   "https://*.successfactors.com/*"  `

**Comment by cgrail** [comment]
@patricematignon I could do that, but then the extension would also be active for all successfactors pages and you probably don't want that. Can you please be a little bit more specific?
Like
```
"https://github.successfactors.com/*"
or
"https://*.successfactors.com/github"
```

**Comment by patricematignon** [comment]
Sorry I haven't responded at the time, we moved away from this domain name.

There is a new GHE instance in the DMZ : https://github.tools.sap/ coudl this one be added maybe ?

**Comment by cgrail** [comment]
I can add it. It just might take a while as I'm currently pretty busy and I'm not able to build the old source code. Something with Flow has changed. So I'll need to rewrite the whole code to TypeScript to be able to build it again. I don't know when I'm able to do that.
